timezone: 'Europe/Berlin'
google_developer_key: ''
ignore_video_title: 
- '|'
- '*'
- '('
- ')'
- '['
- ']'
- 'video'
- 'hd'
- 'featuring'
- 'official'
- 'feat.'
- 'ft.'
- 'music'
- 'soundtrack'
- 'lyric'
- 'lyrics'
- 'officiel'
- 'youtube'
- 'spot'